import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });
const baseUrl = "https://api.fitbit.com";

export default function Home() {
  const { data: session, status } = useSession();

  useEffect(() => {
    console.log(session, status);
    if (status === "authenticated") {
      fetch("/api/auth/jwt").then((body) => {
        console.log(body);
      });
      fetch(
        "https://api.fitbit.com/1.2/user/-/sleep/date/2023-03-08/2023-03-22.json"
      )
        .then((response) => {
          console.log("fitbit request", response);
          return response.json();
        })
        .then((body) => {
          console.log("body", body);
        });
    }
  }, [session, status]);

  function handleClick() {
    signIn();
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleClick}>Signin with Fitbit</button>
      </main>
    </>
  );
}
